name: Change Duck

on:
    issues:
      types: [opened]

jobs:
    table-update:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                if [ -f DUCK/requirements.txt ]; then pip install -r DUCK/requirements.txt; fi
        
        - name: run python
          run: |
            python DUCK/main.py
          env :
            ISSUE_TITLE : ${{ github.event.issue.title }}
            ISSUE_NUMBER : ${{ github.event.issue.number }}
            ISSUE_OWNER : ${{ github.event.issue.user.login }}

    