name: Change Duck

on:
    issues:
      types: [opened]

jobs:
    duck-update:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: duckpandemic
          uses: tot0p/duckpandemic@v1.1.0
          
    
