name: Change Duck

on:
    issues:
      types: [opened]

jobs:
    duck-update:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: duckpandemic
          uses: tot0p/duckpandemic@9362589b094e14f97792663050a36fd56333d969 # v1.2.0
          
    
