name: Build and Deploy Eleventy Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'site/package-lock.json'
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Build site
        working-directory: ./site
        run: npm run build
      - name: Deploy to Github Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Remove existing files (but keep .git and .github)
          find . -maxdepth 1 -not -name '.git' -not -name '.github' -not -name 'site' -not -name '.' -exec rm -rf {} +
          # Copy built site to root
          cp -r site/_site/* .
          # Add and commit changes
          git add .
          git commit -m "Deploy site" || exit 0
          git push origin HEAD:gh-pages --force