# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Readme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron:  '0 2 * * *'

jobs:
  table-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f TABLE/requirements.txt ]; then pip install -r TABLE/requirements.txt; fi
    - name: run python
      run: |
        python TABLE/main.py
            
  wakatime-update:
    needs: ["table-update"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f WAKATIME/requirements.txt ]; then pip install -r WAKATIME/requirements.txt; fi
    - name: run python
      run: |
        python WAKATIME/main.py
      env : 
        WAKATIME_API_KEY : ${{ secrets.WAKATIME_API_KEY }}
