# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Readme

on:
  schedule:
  - cron:  '0 7 * * *'
  push:
    branches:
      - main

jobs:
  table-update:
    runs-on: ubuntu-latest

    steps:
    - name: List top repositories
      uses: tot0p/top-repo-action@v1
      with:
          username: tot0p
          include_org_repos: true # Optional (default: false)
            
  wakatime-update:
    needs: ["table-update"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Pull
      run: git pull
    - name: wakatime update
      uses: tot0p/wakatime-readme@v1
      with:
        WAKATIME_API_KEY : ${{ secrets.WAKATIME_API_KEY }}
        CHAR1 : ">"
        CHAR2 : "-"
        draw_graph: "true"

